### PR TITLE
Upgrade to d3 v4 and extract endpoints to variables

### PR DESCRIPTION
**Pull request by colindean**
The vertical lines are no longer showing and I can't figure out why. I don't really know what I'm doing in d3.

Extracting API endpoints into variables will let people change to an enterprise setup. I'm working on also adding auth token support.

### CODE REVIEW

**Comment by scribu** [comment]
Is there any particular reason for wanting to upgrade D3? I noticed several users attempting this and I'm not quite sure why.

Regarding the vertical bars that don't go all the way down, I noticed this error in the Chrome console:

```
Error: <rect> attribute width: Expected length, "NaN".
```

**Comment by colindean** [comment]
Honestly, upgrading D3 was the first thing I did because I couldn't figure out what version was vendored, and the API documentation didn't seem to match what was vendored. So, it seemed worth my time to upgrade and then basically mess around until I figured out what changed between the version vendored and v4.

If I have more time, I'll look into the vertical bars thing. It'd be great if you could poke at it; you're definitely more aware of D3 than I, who just messed around with it for the first time a few hours ago.

**Comment by scribu** [comment]
> Honestly, upgrading D3 was the first thing I did because I couldn't figure out what version was vendored, and the API documentation didn't seem to match what was vendored.

Ah, yes. That was a mistake. [This commit](https://github.com/scribu/travis-stats/commit/cb5da0b40fdbc8b41089a6b4615102fb932c006b) would suggest that v2 was the previous version.

I'm no D3 expert either. I basically copied the example code from the D3 site and made some minor tweaks. That was two years ago. 😸

**Comment by scribu** [comment]
Closing in favour of #7.

**Pull request closed without merging**
