### PR TITLE
Adds ability to change endpoint and token

### PR DESCRIPTION
**Pull request by colindean**
And changes persistence. I realize this is a breaking change :-/

Probably let #5 through first, unless you like how I've done this enough to merge this _instead of_ #5.

### CODE REVIEW

**Comment by scribu** [comment]
Hey Colin, thanks for the PR!

> I realize this is a breaking change :-/

That could be avoided by adding the extra config information as query parameters:

http://scribu.github.io/travis-stats/#scribu/romania-3d?travis_endpoint=magnum.travis.com&travis_api_endpoint=...

That's a bit more work to parse, but worthwhile IMO.

However, before exploring that further, I'm concerned about the security implications of passing the API token in the URL.

For instance, index.html has Google Analytics enabled, which I'm pretty sure can track URL fragments. This means that I could see the API tokens submitted by any user of the app.

**Comment by scribu** [comment]
To make this secure, the frontend would need to fetch the auth token from somewhere, after the user has provided some proof that they have access to it.

Ideally, that flow would look like this:

1. Frontend sends the user to some special Travis URL.
2. The user logs in (if not already logged in).
3. That special Travis URL sends an API token to the frontend browser window.

**Comment by scribu** [comment]
A simpler solution would be to keep the extra UI in this PR, but store the data in `localStorage`.

**Comment by scribu** [comment]
Regarding the vertical bars that don't go all the way down, I noticed this error in the Chrome console:

```
Error: <rect> attribute width: Expected length, "NaN".
```

**Comment by scribu** [comment]
Oh, actually, let's discuss the D3 stuff in #5.

**Comment by colindean** [comment]
Good point about exposing the API token via Google Analytics. Maybe a quick fix is to disable GA when the API endpoint is changed from public Travis?

I think the first thing I'll do is move to the query parameter method. It's more work, but it looks a little cleaner in addition to not breaking backwards compatibility.

I don't know when next I'll have time to do this, though.

**Comment by scribu** [comment]
> Good point about exposing the API token via Google Analytics. Maybe a quick fix is to disable GA when the API endpoint is changed from public Travis?

That would be quite hacky. Did you see [this](https://github.com/scribu/travis-stats/pull/6#issuecomment-239032200) comment?

**Comment by scribu** [comment]
I guess my actual question is: Do you have a specific usecase in mind that would _require_ passing the API token in the URL? I know it's convenient, but it's really not a good practice at all.

**Comment by colindean** [comment]
Looks like Travis doesn't offer an auth dance yet: https://docs.travis-ci.com/api/#authentication

> In the future, we are planning to add a proper OAuth handshake for third party applications.

Ideally, I want a way to pass around a URL that allows my coworkers to see the stats without having to set the API information manually. A login dance would be OK.

What about a per-instance config file? E.g. `api-settings.jsonp` or something like that, which just has something like:

```javascript
apiSettings({
  endpoint: 'travis.mycompany.com',
  api_endpoint: 'travis.mycompany.com/api',
  token: 'd34db33f'
});
```

The file is loaded async.

This is enough for my use case of "I want to see this graph for my Travis Enterprise projects."

**Comment by scribu** [comment]
A JSON config file could work (it doesn't need to be JSONP, since it would come from the same domain).

If index.html is loaded from http://your-domain.com/travis-stats/ then the script would try to load the settings from http://your-domain.com/travis-stats/api-settings.json

This would enable having multiple instances on the same domain. Here's how the directory layout would look like on your server:

/var/www/public-html/
  travis-stats/
    index.html
    api-settings.json
    css/
    js/
  another-instance/
    index.html
    api-settings.json
    css/
    js/

And it could be made secure by adding basic auth in front of all the files. (this would be done by configuring nginx or apache or whatever server is used on the backend).

**Comment by scribu** [comment]
Closing in favour of #7.

**Pull request closed without merging**
